trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  pool: Linux
  steps:
  - checkout: self

- stage: Deploy
  pool:
    name: Local
    demands: docker
  jobs:
  - deployment: Deploy
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: 'echo "Test Step"'
