trigger:
- master

resources:
- repo: self

stages:
# - stage: Build
#   pool: Linux
#   steps:
#   - checkout: self

- stage: Deploy
  pool: Linux
  jobs:
  - deployment: Deploy
    environment: Prod
    strategy:
      runOnce:
        deploy:
          # pool: UnMango-Local
          steps:
          - task: DockerInstaller@0
            displayName: Docker Installer
            inputs:
              dockerVersion: 17.09.0-ce
              releaseType: stable
              
          - bash: |
              curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` -o docker-compose
              chmod +x docker-compose
          
          - task: DockerCompose@0
            displayName: Run services
            inputs:
              action: Run services
              dockerComposeFile: '**/docker-compose.yml'
              projectName: $(Build.Repository.Name)
              qualifyImageNames: true
              buildImages: true
              abortOnContainerExit: true
              detached: false
