trigger:
- master

resources:
- repo: self

stages:
# - stage: Build
#   pool: Linux
#   steps:
#   - checkout: self

- stage: Deploy
  pool: Linux
  jobs:
  - deployment: Deploy
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: 'echo "Test Step"'
