trigger:
- master

resources:
- repo: self

stages:
# - stage: Build
#   pool: Linux
#   steps:
#   - checkout: self

- stage: Deploy
  pool: Linux
  jobs:
  - deployment: Deploy
    environment: Prod
    strategy:
      runOnce:
        deploy:
          # pool: UnMango-Local
          steps:
          - bash: 'echo "Test Step"'
          
          - task: DockerCompose@0
            displayName: Run services
            inputs:
              action: Run services
              dockerComposeFile: '**/docker-compose.yml'
              projectName: $(Build.Repository.Name)
              qualifyImageNames: true
              buildImages: true
              abortOnContainerExit: true
              detached: false
